[package]
name = "static-dep"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"] # Can not compile successfully
# crate-type = ["cdylib","dylib","rlib"] # Compile successfully

[dependencies]
